version: "3"
services:
  backend:
    build: .
  frontend:
    build: frontend
  gateway:
    image: nginx:1.23.1-alpine
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "5000:80"